# Generated by Django 3.1.3 on 2020-12-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201209_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='media',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nota2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
